name: Java with Gradle

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Source Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    # jar file build and permissions
    - name: Grant jar
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build bootJAR

    # runner(ubuntu) docker buildx install
    - name: Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    # docker login
    - name: Docker Login
      run: docker/setup-buildx-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    # docker image build to push docker hub
    - name: Push image
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        platforms: 
        push: true
        # DOCKER BUILD -T JSLIM9413/IMAGE/TAGS
        tags: ${{ secrets.DOCKER_USERNAME }}/springapp:${{ github.sha }}


        


      

